import type { FastifyInstance } from 'fastify';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { BUILD_SHA, BUILD_SHA_SHORT, BUILD_BRANCH, BUILT_AT } from '../build-info.js';

interface VersionInfo {
  sha: string;
  shaFull: string;
  branch: string | null;
  builtAt: string;
}

// /version now reflects the binary that the currently-running Node process was
// built from. Previous implementation read .git/refs/heads/main at request time,
// which would update on every `git pull` during deploy — even if the subsequent
// migrate or service restart step failed and the running Node never picked up
// the new code. That made the topbar lie about the running version and
// produced hard-to-spot deploy-half-failures. build-info.ts is generated by
// scripts/build-info.mjs at npm-build time (and gitignored).
function readVersion(): VersionInfo {
  return {
    sha: BUILD_SHA_SHORT,
    shaFull: BUILD_SHA,
    branch: BUILD_BRANCH,
    builtAt: BUILT_AT,
  };
}

async function readDocsHtml(): Promise<string> {
  // dist runs from C:\Apps\ITDashboard\apps\server\dist; docs/ is at C:\Apps\ITDashboard\docs
  const docPath = join(process.cwd(), '..', '..', 'docs', 'dashboard.html');
  try {
    return await readFile(docPath, 'utf8');
  } catch {
    return '<!doctype html><html><body><h1>Documentation file not found</h1><p>Expected at <code>docs/dashboard.html</code></p></body></html>';
  }
}

export async function registerVersionRoutes(app: FastifyInstance) {
  app.get('/version', async () => readVersion());
  // Convenience aliases for the smoke test in deploy.yml — easy to grep / diff.
  app.get('/version/sha', async () => readVersion().sha);

  const DOCS_CSP = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'";

  app.get('/docs', async (_req, reply) => {
    const html = await readDocsHtml();
    // Docs is static read-only content. Helmet's default CSP (script-src 'self')
    // blocks the inline `onclick="window.print()"` button and any future inline
    // toggles (e.g. CS/EN language switch). Override CSP to allow inline scripts
    // for this single route — the page never accepts user input and has no
    // privileged context.
    reply.header('Content-Security-Policy', DOCS_CSP);
    reply.type('text/html; charset=utf-8').send(html);
  });

  // The other static doc pages next to dashboard.html — the bilingual system
  // presentation, project status, the MAC/hostname write-up. Allow-listed by name
  // (no path traversal); same relaxed CSP. Their relative cross-links resolve
  // under /docs/ so the CS↔EN presentation switch works.
  const DOC_FILES = new Set([
    'dashboard.html', 'prezentace-system.html', 'presentation-system.html',
    'project-status.html', 'nacitani-mac-hostname.html',
  ]);
  app.get<{ Params: { file: string } }>('/docs/:file', async (req, reply) => {
    const file = req.params.file;
    if (!DOC_FILES.has(file)) { reply.code(404).type('text/html').send('<!doctype html><h1>404 — dokument nenalezen</h1>'); return; }
    try {
      const html = await readFile(join(process.cwd(), '..', '..', 'docs', file), 'utf8');
      reply.header('Content-Security-Policy', DOCS_CSP);
      reply.type('text/html; charset=utf-8').send(html);
    } catch {
      reply.code(404).type('text/html').send('<!doctype html><h1>404 — dokument nenalezen</h1>');
    }
  });
}
