#!/usr/bin/env node
// Generates src/build-info.ts with the git SHA captured AT BUILD TIME.
// Imported by version.ts so /version reflects the running binary, not whatever
// .git/refs/heads/main currently points to. Before this script existed, a
// failed migration could leave a stale Node serving old code while the topbar
// SHA happily updated from the freshly-pulled git ref — diagnostic gaslighting.
import { execSync } from 'node:child_process';
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname } from 'node:path';

const target = new URL('../src/build-info.ts', import.meta.url);
const targetPath = decodeURIComponent(target.pathname).replace(/^\//, '');

// Prefer CI-provided env vars (GitHub Actions sets GITHUB_SHA / GITHUB_REF_NAME)
// because the runtime location on the production server is a robocopy'd source
// tree without a .git directory — `git rev-parse` would yield 'unknown' and
// the deploy smoke test would fail on SHA mismatch.
let sha = process.env.GITHUB_SHA || process.env.GIT_SHA || 'unknown';
let branch = process.env.GITHUB_REF_NAME || process.env.GIT_BRANCH || null;
if (sha === 'unknown') {
  try {
    sha = execSync('git rev-parse HEAD', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch { /* not a git checkout */ }
}
if (!branch) {
  try {
    branch = execSync('git rev-parse --abbrev-ref HEAD', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
    if (branch === 'HEAD') branch = null;
  } catch { /* detached or no git */ }
}

const builtAt = new Date().toISOString();

const dir = dirname(targetPath);
if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

const content = `// Generated by scripts/build-info.mjs at build time. Do not edit.
export const BUILD_SHA = ${JSON.stringify(sha)};
export const BUILD_SHA_SHORT = ${JSON.stringify(sha.slice(0, 7))};
export const BUILD_BRANCH = ${JSON.stringify(branch)};
export const BUILT_AT = ${JSON.stringify(builtAt)};
`;
writeFileSync(targetPath, content, 'utf8');
console.log(`build-info.ts written: ${sha.slice(0, 7)} (${branch ?? 'detached'}) @ ${builtAt}`);
